name: API CI
#on: [push]

#Esta configuracion es por si no tienes vincula al github
on:
  push:
    paths:
      -"./api/**"
      -"github/workflows/api-ci.yml"

defaults:
  run:
    working-directory: ./api
#Esto lo correra en una maquina remota que lo hara desde github
jobs:
  unit-test:
    run-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json
      - name: install
        shell: bash
        run: npm ci
      - name: run unit test
        shell: bash
        run: npm run test
